### ISSUE TITLE
Add CORS by default

### ISSUE THREAD

**Issue by alexdanilowicz** [fern-api/express-starter#11]
Install cors package and add:

`app.use(cors())` before the register command.

Otherwise user will run into cors errors. I feel like most express-starter kits allow for cors.

**Comment by zachkirsch** [comment]
Yeah good point, will fix!

**Comment by dsinghvi** [comment]
@Shield01 go for it!

**Comment by Danities316** [comment]
Hi @Shield01 are you still working on this?

If you are caught up  with work, I can work on it if that is ok by you.

@dsinghvi is this issue still open?

**Comment by zachkirsch** [comment]
This was fixed by #12

**Comment by Danities316** [comment]
@zachkirsch oh that is great. Thanks
